- name: psi
  replicas: 1
  spec:
    containers:
      - command:
          - sh
        args:
          - -c
          - "/root/main --kuscia /etc/kuscia/task-config.conf"
        configVolumeMounts:
          - mountPath: /etc/kuscia/task-config.conf
            subPath: task-config.conf
        name: psi
        ports:
          - name: psi
            port: 54509
            protocol: GRPC
            scope: Cluster
        workingDir: /work
    restartPolicy: Never
