# Copyright 2023 Ant Group Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@1.3.0
  continuation: circleci/continuation@1.1.0

parameters:
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Event:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""
  run-schedule:
    type: boolean
    default: false

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  lint:
    # Use machine executor for convenient data sharing between the host and docker-compose cluster
    docker:
      - image: secretflow/lint-ci:latest
    resource_class: medium
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - run:
          name: Checkout devtools
          command: git clone https://github.com/secretflow/devtools.git ../devtools
      - run:
          name: Whitespace check
          command: bash ../devtools/lint-whitespace.sh
  docs_publish:
    docker:
      - image: cimg/python:3.10-node
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - run:
          name: Build docs and publish
          command: |
            set -ex
            cd docs
            export DRY_RUN=0
            export DOCTOOLS_PUBLISH_NPM_TOKEN=${DOCTOOLS_PUBLISH_NPM_TOKEN}
            sudo apt-get update && sudo apt install -y git
            python3 -m venv ~/.venv/docs
            source ~/.venv/docs/bin/activate
            python -m pip install -r requirements.txt
            secretflow-doctools build --lang zh_CN --lang en
            secretflow-doctools publish \
              --name @secretflow/x-psi \
              --index-js _build/esm/index.js

workflows:
  unittest-workflow:
    when:
      and:
        - not: << pipeline.parameters.run-schedule >>
        - not: << pipeline.parameters.GHA_Action >>
        - not: << pipeline.parameters.GHA_Meta >>
    jobs:
      - path-filtering/filter:
          base-revision: main
          config-path: .circleci/test.yml
          tag: "3.9"
          mapping: |
            psi/.* build-and-run true
            bazel/.* build-and-run true
            MODULE.bazel build-and-run true
            .bazelrc build-and-run true
            .circleci/test.yml build-and-run true
      - lint
      - docs_publish:
          filters:
            branches:
              only: main
            tags:
              only: /^v.*/
  publish-workflow:
    when:
      equal: ["publish_docker_image", << pipeline.parameters.GHA_Meta >>]
    jobs:
      - continuation/continue:
          configuration_path: .circleci/release.yml
          # This is mandatory to trigger a pipeline when pushing a tag
          filters:
            tags:
              only: /.*/
