name: Feature request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]
assignees:
  - 6fj
  - qxzhou1010
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this fature request!
  - type: textarea
    attributes:
      label: Related problem
      description: Is your feature request related to a problem? Please describe.
      placeholder: |
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Solution
      description: Describe the solution you'd like.
      placeholder: |
        A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives
      description: Describe alternatives you've considered.
      placeholder: |
        A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Additional context you would like to provide.
      placeholder: |
        Add any other context or screenshots about the feature request here.
    validations:
      required: true
