version: '3.8'
services:
  psi-sender:
    entrypoint:
      - bash
      - -c
      - "bash /data/setup_wan.sh && ${SENDER_RUN}"
    image: ${IMAGE_WITH_TAG}
    cap_add:
      - NET_ADMIN
    volumes:
      - ./config/:/home/admin/psi/conf/
      - ./tmp_data/:/data
      - ./setup_wan.sh:/data/setup_wan.sh
    deploy:
      resources:
        limits:
          cpus: '${ALICE_CPU_LIMIT}'
          memory: ${ALICE_MEMORY_LIMIT}
  psi-receiver:
    entrypoint:
      - bash
      - -c
      - "bash /data/setup_wan.sh && ${RECEIVER_RUN}"
    image: ${IMAGE_WITH_TAG}
    cap_add:
      - NET_ADMIN
    volumes:
      - ./config/:/home/admin/psi/conf/
      - ./tmp_data/:/data
      - ./setup_wan.sh:/data/setup_wan.sh
    deploy:
      resources:
        limits:
          cpus: '${BOB_CPU_LIMIT}'
          memory: ${BOB_MEMORY_LIMIT}
